import collections
from enum import Enum


class Account(Enum):
    HDFC_BANK_ACCOUNT = 1
    KOTAK_BANK_ACCOUNT = 2
    HDFC_CREDIT_CARD = 3
    HDFC_TATA_NEU_CREDIT_CARD = 13
    SBI_CREDIT_CARD = 4
    ICICI_CREDIT_CARD = 5
    KOTAK_CREDIT_CARD = 6
    EQUITAS_BANK_ACCOUNT = 7
    HDFC_UPI_CREDIT_CARD = 8
    PAYTM_WALLET = 9
    IDFC_BANK_ACCOUNT = 10
    FASTAG_WALLET = 11
    SBI2_CREDIT_CARD = 12
    SBI3_CREDIT_CARD = 14
    AXIS_CREDIT_CARD = 15
